# Generated by Django 2.2.4 on 2019-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190827_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='status',
            field=models.CharField(choices=[('N', 'Non completata'), ('C', 'Completata'), ('R', 'Rimossa')], default='N', max_length=1),
        ),
    ]
